apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: brxm-repo-maintainer
spec:
  schedule: " 0 */4 * * *" #every 4 hours
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: brxm-repo-maintainer
          containers:
            - name: brxm-repo-maintainer
              image: com.github.bcanvural/brxm-repo-maintainer:0.0.1-SNAPSHOT
              env:
                - name: APP_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: BRXM_SELECTOR
                  value: "app=brxm"
                - name: "POSTGRES_DB_HOST"
                  value: "postgres-helm-postgresql.default.svc.cluster.local"
                - name: "POSTGRES_DB_PORT"
                  value: "5432"
                - name: "POSTGRES_DB_NAME"
                  value: "brxmdb"
                - name: "POSTGRES_DB_USER"
                  value: "postgres"
                - name: "POSTGRES_DB_PASSWORD"
                  value: "mypass"
                - name: "POSTGRES_DB_DRIVER"
                  value: "org.postgresql.Driver"
          restartPolicy: OnFailure